### ISSUE TITLE
paadleseg的docker镜像在自定义数据集上运行train.py出现 Cudnn error, CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by fangchuan** [PaddlePaddle/PaddleSeg#1243]
paddlepaddle: 自编译， release/2.1 分支
编译环境: docker: latest-gpu-cuda10.1-cudnn7-gcc82-dev
本机环境: Ubuntu18.04   Driver Version: 418.181.07   CUDA Version: 10.1, 无法找到cudnn版本信息; GPU显存11G

完成paddlepaddle编译后, 正常安装paddleseg.
1. 运行教程[模型训练示例](https://paddleseg.readthedocs.io/zh_CN/release-2.1/train/train.html#id1) , 正常运行结束:

> ------------Environment Information-------------
platform: Linux-4.15.0-153-generic-x86_64-with-debian-stretch-sid
Python: 3.7.0 (default, Apr 22 2021, 05:45:43) [GCC 8.2.0]
Paddle compiled with cuda: True
NVCC: Cuda compilation tools, release 10.1, V10.1.243
cudnn: 7.6
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: GeForce GTX']
GCC: gcc (GCC) 8.2.0
PaddlePaddle: 2.1.2
OpenCV: 4.5.3
W0809 12:24:56.373420    18 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.1, Runtime API Version: 10.1
W0809 12:24:56.373437    18 device_context.cc:422] device: 0, cuDNN Version: 7.6. 

2. 运行自定义数据集报下面错误:

> platform: Linux-4.15.0-153-generic-x86_64-with-debian-stretch-sid
Python: 3.7.0 (default, Apr 22 2021, 05:45:43) [GCC 8.2.0]
Paddle compiled with cuda: True
NVCC: Cuda compilation tools, release 10.1, V10.1.243
cudnn: 7.6
GPUs used: 1
CUDA_VISIBLE_DEVICES: 0
GPU: ['GPU 0: GeForce GTX']
GCC: gcc (GCC) 8.2.0
PaddlePaddle: 2.1.2
OpenCV: 4.5.3
W0809 12:33:38.582741   211 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.1, Runtime API Version: 10.1
W0809 12:33:38.582756   211 device_context.cc:422] device: 0, cuDNN Version: 7.6.
2021-08-09 12:33:41 [INFO]	Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
2021-08-09 12:33:41 [INFO]	There are 1525/1525 variables loaded into HRNet.
/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/nn/layer/norm.py:641: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/framework.py:706: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  elif dtype == np.bool:
/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py:239: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.float32, but right dtype is paddle.int64, the right dtype will convert to paddle.float32
  format(lhs_dtype, rhs_dtype, lhs_dtype))
Traceback (most recent call last):
  File "train.py", line 190, in <module>
    main(args)
  File "train.py", line 185, in main
    fp16=args.fp16)
  File "/code/PaddleSeg/paddleseg/core/train.py", line 195, in train
    loss.backward()
  File "<decorator-gen-122>", line 2, in backward
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/framework.py", line 227, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 239, in backward
    framework._dygraph_tracer())
OSError: (External)  Cudnn error, CUDNN_STATUS_EXECUTION_FAILED  (at /code/Paddle/paddle/fluid/operators/conv_cudnn_op.cu:790)

自定义config文件:

> ---------------Config Information---------------
batch_size: 1
iters: 160000
loss:
  coef:
        - 1
       - 0.4
  types:
       - ignore_index: 255
       type: CrossEntropyLoss
       - ignore_index: 255
       type: CrossEntropyLoss
    lr_scheduler:
      end_lr: 0
      learning_rate: 0.01
      power: 0.9
      type: PolynomialDecay
    model:
      backbone:
        pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
        type: HRNet_W18
      backbone_indices:
      - 0
      num_classes: 8
      pretrained: null
      type: OCRNet
    optimizer:
      momentum: 0.9
      type: sgd
      weight_decay: 4.0e-05
    train_dataset:
      dataset_root: data/parkinglot
      mode: train
      transforms:
      - max_scale_factor: 2.0
        min_scale_factor: 0.5
        scale_step_size: 0.25
        type: ResizeStepScaling
      - crop_size:
        - 1024
        - 512
        type: RandomPaddingCrop
      - type: RandomHorizontalFlip
      - type: Normalize
      type: Parkinglot
    val_dataset:
      dataset_root: data/parkinglot
      mode: val
      transforms:
      - type: Normalize
      type: Parkinglot
    ------------------------------------------------

已经在paddleseg/datasets目录下添加对应的数据集类, 请问这种错误如何解决? 反复查看了docker 的cuda版本和cudnn版本是没问题的。
 @ZeyuChen @chliang @QingshuChen @sjtubinlong @jacquesqiao    Thanks in advance!

**Comment by nepeplwu** [comment]
@fangchuan 你的数据集标注是否是正确的？label应该是单通道的png，每个pixel的值位于[0 ~ num_class)之间

**Comment by fangchuan** [comment]
> @fangchuan 你的数据集标注是否是正确的？label应该是单通道的png，每个pixel的值位于[0 ~ num_class)之间

谢谢指正, 正是这个问题, 已解决

**Comment by zkzk123zk** [comment]
在版本没有问题的情况下，官方默认使用了多卡训练的方式，我猜你可能只有一张显卡，因此出现了这种错误。在训练配置里，官方的代码是parser.add_argument(
        '--device',
        dest='device',
        help='Device place to be set, which can be GPU, XPU, NPU, CPU',
        default='gpu',
        type=str)
你需要修改为parser.add_argument(
        '--device',
        dest='device',
        help='Device place to be set, which can be GPU, XPU, NPU, CPU',
        default='cuda:0',
        type=str)
我的解决方法是这样的
