### ISSUE TITLE
Out of memory error on GPU 0. Cannot allocate 182.531494MB memory on GPU 0, 22.313599GB memory has been allocated and available memory is only 69.937500MB.

### ISSUE THREAD

**Issue by ZhouFangru** [PaddlePaddle/PaddleSeg#1753]
1. PaddleSeg version: 2.4
 2. PaddlePaddle version: 2.1.3
 3. Operation system: Linux
 4. Python version: 3.8.10
 5. CUDA/cuDNN version: CUDA9.0/cuDNN 7.6.5

您好，我在训练人体分割任务时，显存一直增加(从训练开始实时监测gpu从3G一直增加到22G)，最后出现
![image](https://user-images.githubusercontent.com/24693920/151310523-0f762b6c-8c1d-4fea-aaa8-410bfbcb1dac.png)

该任务在PP-HumanSeg（https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.4/contrib/PP-HumanSeg
）文件夹下运行命令：
`python train.py --config configs/fcn_hrnetw18_small_v1_humanseg_192x192_mini_supervisely.yml --save_dir saved_model/fcn_hrnetw18_small_v1_humanseg_192x192_mini_superviselyy`
尝试过在运行命令之前添加以下代码，仍然会在训练到4400迭代时out of memory.
`FLAGS_fraction_of_gpu_memory_to_use=0.4`

**Comment by haoyuying** [comment]
稳定时候的显存占用是多少呢，使用的图片的大小是多少，是192*192吗

**Comment by ZhouFangru** [comment]
从开始监测显存就一直在增加，好像没有稳定在一个数值。
图片的大小是192*192，batch_size是64
![image](https://user-images.githubusercontent.com/24693920/151315850-445e9166-fa4e-4a9f-bfbe-0ba12dd10e77.png)

**Comment by haoyuying** [comment]
先把batchsize调小一些看看有没有能稳定的数值，如果还是一直增长，可以反馈给我们。

**Comment by ZhouFangru** [comment]
之前试过batch_size=2,也是一直增长（只不过从很小的值开始增长）。
感觉应该和batch_size关系不大，毕竟就算batch_size=64,也是训练了4400次迭代才out of memory。感觉好像是训练过程中有什么占用显存没有释放。

**Comment by haoyuying** [comment]
可以尝试下把paddle升到最新版本

**Comment by ZhouFangru** [comment]
将paddle更新到2.2.2，问题已解决，感谢~

**Comment by fschvart** [comment]
I have the latest version, Paddle-gpu 2.3.0 and I suffer from the same problem. Is there any other fix?
