### ISSUE TITLE
[Bug] An issue of SemanticConnectivityloss

### ISSUE THREAD

**Issue by CuberrChen** [PaddlePaddle/PaddleSeg#2466]
platform: Linux-4.15.0-140-generic-x86_64-with-debian-stretch-sid
Python: 3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
Paddle compiled with cuda: True
NVCC: Cuda compilation tools, release 10.1, V10.1.243
cudnn: 7.6
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: Tesla V100-SXM2-32GB']
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0
PaddleSeg: 2.4.0
PaddlePaddle: 2.3.0-rc0
OpenCV: 4.1.1

---

BUG:

```
  File "/home/aistudio/project/paddleseg/models/losses/semantic_connectivity_loss.py", line 153, in forward
    pred_i, real_label_num, real_pred_num, zero)
  File "/home/aistudio/project/paddleseg/models/losses/semantic_connectivity_loss.py", line 184, in compute_class_connectiveity
    pair_conn_sum = paddle.to_tensor([0.], stop_gradient=False)
  File "<decorator-gen-159>", line 2, in to_tensor
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddle/fluid/framework.py", line 395, in __impl__
    return func(*args, **kwargs)
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddle/tensor/creation.py", line 189, in to_tensor
    stop_gradient=stop_gradient)
OSError: (External) CUDA error(719), unspecified launch failure. 
  [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:258)
```

---

Expect a quick reply,
Thanks.

**Comment by Bobholamovic** [comment]
Please provide a minimal example to reproduce this bug.

**Comment by CuberrChen** [comment]
The problem has been solved. I used the originally released version of paddleseg with bugs.
