### ISSUE TITLE
tabulate: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered. (at ..\paddle\fluid\imperative\tracer.cc:307)

### ISSUE THREAD

**Issue by Destinycjk** [PaddlePaddle/PaddleSeg#2761]
1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.6）
 2. PaddlePaddle版本：（如PaddlePaddle 2.3.1）
 3. 操作系统信息：（如Windows）
 4. Python版本号：（如Python3.8）
 5. CUDA/cuDNN版本：（ 如CUDA11.6/cuDNN 8.5等）

您好，我在实现PanopticDeepLab时，参考帮助文档，训练过程没有任何问题，但是在验证或者预测时，均出现报错：tabulate: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered. (at ..\paddle\fluid\imperative\tracer.cc:307)
完整日志流程如下：
2022-11-24 22:01:37 [INFO]
---------------Config Information---------------
batch_size: 8
iters: 90000
learning_rate:
  decay:
    end_lr: 0.0
    power: 0.9
    type: poly
  value: 5.0e-05
loss:
  coef:
  - 1
  - 200
  - 0.001
  types:
  - top_k_percent_pixels: 0.2
    type: CrossEntropyLoss
  - reduction: none
    type: MSELoss
  - reduction: none
    type: L1Loss
model:
  align_corners: true
  aspp_out_channels: 256
  aspp_ratios:
  - 1
  - 3
  - 6
  - 9
  backbone:
    output_stride: 32
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
    type: ResNet50_vd
  backbone_indices:
  - 2
  - 1
  - 0
  - 3
  decoder_channels: 256
  instance_aspp_out_channels: 256
  instance_class_key:
  - center
  - offset
  instance_decoder_channels: 128
  instance_head_channels: 32
  instance_low_level_channels_projects:
  - 64
  - 32
  - 16
  instance_num_classes:
  - 1
  - 2
  low_level_channels_projects:
  - 128
  - 64
  - 32
  type: PanopticDeepLab
optimizer:
  type: adam
train_dataset:
  dataset_root: data/cityscapes
  ignore_stuff_in_offset: true
  mode: train
  small_instance_area: 4096
  small_instance_weight: 3
  transforms:
  - max_scale_factor: 2.0
    min_scale_factor: 0.5
    scale_step_size: 0.25
    type: ResizeStepScaling
  - crop_size:
    - 1025
    - 513
    label_padding_value:
    - 0
    - 0
    - 0
    type: RandomPaddingCrop
  - type: RandomHorizontalFlip
  - brightness_range: 0.4
    contrast_range: 0.4
    saturation_range: 0.4
    type: RandomDistort
  - type: Normalize
  type: CityscapesPanoptic
val_dataset:
  dataset_root: data/cityscapes
  ignore_stuff_in_offset: true
  mode: val
  small_instance_area: 4096
  small_instance_weight: 3
  transforms:
  - label_padding_value:
    - 0
    - 0
    - 0
    target_size:
    - 2049
    - 1025
    type: Padding
  - type: Normalize
  type: CityscapesPanoptic
------------------------------------------------
W1124 22:01:38.334636  5108 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.8, Runtime API Version: 11.6
W1124 22:01:38.334636  5108 gpu_resources.cc:91] device: 0, cuDNN Version: 8.5.
2022-11-24 22:01:39 [INFO]      Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
2022-11-24 22:01:39 [INFO]      There are 275/275 variables loaded into ResNet_vd.
2022-11-24 22:01:39 [INFO]      Loading pretrained model from output/iter_90000/model.pdparams
2022-11-24 22:01:41 [INFO]      There are 461/461 variables loaded into PanopticDeepLab.
2022-11-24 22:01:41 [INFO]      Loaded trained params of model successfully
2022-11-24 22:01:41 [INFO]      Start evaluating (total_samples=500, total_iters=500)...
C:\ProgramData\Anaconda3\envs\PaddleSeg\lib\site-packages\paddle\fluid\dygraph\math_op_patch.py:276: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.float32, but right dtype is paddle.bool, the right dtype will convert to paddle.float32
  warnings.warn(
C:\ProgramData\Anaconda3\envs\PaddleSeg\lib\site-packages\paddle\fluid\dygraph\math_op_patch.py:276: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.int64, but right dtype is paddle.float32, the right dtype will convert to paddle.int64
  warnings.warn(
C:\ProgramData\Anaconda3\envs\PaddleSeg\lib\site-packages\paddle\fluid\dygraph\math_op_patch.py:276: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.int64, but right dtype is paddle.bool, the right dtype will convert to paddle.int64
  warnings.warn(
W1124 22:01:44.624392 18832 system_allocator.cc:210] cudaHostAlloc failed.
W1124 22:01:44.624392 18832 naive_best_fit_allocator.cc:573] cudaHostAlloc Cannot allocate 25202700 bytes in CUDAPinnedPlace
Traceback (most recent call last):
  File "val.py", line 111, in <module>
    main(args)
  File "val.py", line 100, in main
    evaluate(
  File "D:\BUAA_CK\CODE\PaddleSeg\PaddleSeg-release-2.6\contrib\PanopticDeepLab\core\val.py", line 104, in evaluate
    semantic, semantic_softmax, instance, panoptic, ctr_hmp = infer.inference(
  File "D:\BUAA_CK\CODE\PaddleSeg\PaddleSeg-release-2.6\contrib\PanopticDeepLab\core\infer.py", line 336, in inference
    panoptic = merge_semantic_and_instance(semantic, instance, label_divisor,
  File "D:\BUAA_CK\CODE\PaddleSeg\PaddleSeg-release-2.6\contrib\PanopticDeepLab\core\infer.py", line 252, in merge_semantic_and_instance
    v, c = paddle.unique(sem_ins_id, return_counts=True)
  File "C:\ProgramData\Anaconda3\envs\PaddleSeg\lib\site-packages\paddle\tensor\manipulation.py", line 1226, in unique
    out, inverse, indices, counts = _C_ops.unique(
SystemError: (Fatal) Operator unique raises an class thrust::system::system_error exception.
The exception content is
:tabulate: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered. (at ..\paddle\fluid\imperative\tracer.cc:307)

非常感谢您能在百忙中答疑解惑！

**Comment by wuyefeilin** [comment]
看样子是环境的问题，麻烦提供一下环境信息

**Comment by Destinycjk** [comment]
非常感谢您的回复！
我的主要环境配置为：
PaddleSeg版本：PaddleSeg release/2.6.0
PaddlePaddle版本：PaddlePaddle 2.3.1.post116
操作系统信息：Windows
Python版本号：Python3.8
CUDA/cuDNN版本：CUDA11.6/cuDNN 8.5.0
因为环境主要还是参考教程来的，所以不太清楚问题在哪。另外，官方给出的quick start是能够正常运行的。

**Comment by Destinycjk** [comment]
已解决，环境问题。

**Comment by wuyefeilin** [comment]
切换到2.5分支试试哈
