### ISSUE TITLE
[Bug] paddle 再同一个batch中backward多次会报错

### ISSUE THREAD

**Issue by henryccl** [PaddlePaddle/PaddleSeg#2803]
我在使用paddle实现样本对抗训练时出现了bug。具体来说我按torch的实现过程来进行实现。具体流程如下：

原torch实现如下：

`import os
import sys
from pathlib import Path

import os.path as osp
import numpy as np
import torch
import torch.backends.cudnn as cudnn
import torch.nn.functional as F
import torch.optim as optim
from torch import nn

from advent.model.discriminator import get_fc_discriminator

def train_advent(model, trainloader, targetloader, cfg):

    # SEGMNETATION NETWORK
    model.train()
    model.to(device)
    cudnn.benchmark = True
    cudnn.enabled = True

    # seg maps, i.e. output, level
    d_main = get_fc_discriminator(num_classes=num_classes)
    d_main.train()
    d_main.to(device)

    # OPTIMIZERS
    # segnet's optimizer
    optimizer = optim.SGD(model.optim_parameters(cfg.TRAIN.LEARNING_RATE),
                          lr=cfg.TRAIN.LEARNING_RATE,
                          momentum=cfg.TRAIN.MOMENTUM,
                          weight_decay=cfg.TRAIN.WEIGHT_DECAY)

    optimizer_d_main = optim.Adam(d_main.parameters(), lr=cfg.TRAIN.LEARNING_RATE_D,
                                  betas=(0.9, 0.99))

    # labels for adversarial training
    source_label = 0
    target_label = 1
    trainloader_iter = enumerate(trainloader)
    targetloader_iter = enumerate(targetloader)
    for i_iter in tqdm(range(cfg.TRAIN.EARLY_STOP)):

        # reset optimizers
        optimizer.zero_grad()
        optimizer_d_main.zero_grad()

        adjust_learning_rate_discriminator(optimizer_d_main, i_iter, cfg)

        # UDA Training
        # only train segnet. Don't accumulate grads in disciminators
        for param in d_main.parameters():
            param.requires_grad = False
        # train on source
        _, batch = trainloader_iter.__next__()
        images_source, labels, _, _ = batch

        pred_src_aux, pred_src_main = model(images_source.cuda(device))

        loss_seg_src_aux = 0
        loss_seg_src_main = loss_calc(pred_src_main, labels, device)
        loss = cfg.TRAIN.LAMBDA_SEG_MAIN * loss_seg_src_main
        loss.backward()

        # adversarial training ot fool the discriminator
        _, batch = targetloader_iter.__next__()
        images, _, _, _ = batch
        pred_trg_aux, pred_trg_main = model(images.cuda(device))

        d_out_main = d_main(pred_trg_main)
        loss_adv_trg_main = bce_loss(d_out_main, source_label)
        loss = cfg.TRAIN.LAMBDA_ADV_MAIN * loss_adv_trg_main
        loss.backward()

        # Train discriminator networks
        # enable training mode on discriminator networks
        for param in d_main.parameters():
            param.requires_grad = True
        # train with source
        pred_src_main = pred_src_main.detach()
        d_out_main = d_main(pred_src_main)
        loss_d_main = bce_loss(d_out_main, source_label)
        loss_d_main = loss_d_main / 2
        loss_d_main.backward()

        # train with target
        pred_trg_main = pred_trg_main.detach()
        d_out_main = d_main(prob_2_entropy(F.softmax(pred_trg_main)))
        loss_d_main = bce_loss(d_out_main, target_label)
        loss_d_main = loss_d_main / 2
        loss_d_main.backward()

        optimizer.step()
        optimizer_d_main.step()
`

我按照自己的需求进行paddle实现之后：
`import os
import time
from collections import deque
import shutil
import numpy as np
import paddle
import paddle.nn.functional as F

from paddleseg.utils import TimeAverager, calculate_eta, resume, logger, worker_init_fn, Discriminator
from paddleseg.core.val import evaluate

def train(model,
          train_dataset,
          val_dataset=None,
          optimizer=None,
          save_dir='output',
          iters=10000,
          batch_size=2,
          resume_model=None,
          save_interval=1000,
          log_iters=10,
          num_workers=0,
          use_vdl=False,
          losses=None,
          keep_checkpoint_max=5,
          test_config=None,
          fp16=False):
    model.train()
    nranks = paddle.distributed.ParallelEnv().nranks
    local_rank = paddle.distributed.ParallelEnv().local_rank

    start_iter = 0
    if resume_model is not None:
        start_iter = resume(model, optimizer, resume_model)

    if not os.path.isdir(save_dir):
        if os.path.exists(save_dir):
            os.remove(save_dir)
        os.makedirs(save_dir)

    if nranks > 1:
        paddle.distributed.fleet.init(is_collective=True)
        optimizer = paddle.distributed.fleet.distributed_optimizer(
            optimizer)  # The return is Fleet object
        ddp_model = paddle.distributed.fleet.distributed_model(model)

    batch_sampler = paddle.io.DistributedBatchSampler(
        train_dataset, batch_size=batch_size, shuffle=True, drop_last=True)

    loader = paddle.io.DataLoader(
        train_dataset,
        batch_sampler=batch_sampler,
        num_workers=num_workers,
        return_list=True,
        worker_init_fn=worker_init_fn,
    )

    # 定义判别器的优化
    discriminator = Discriminator()
    bce_loss = paddle.nn.BCELoss()
    optimizer_d = paddle.optimizer.Adam(learning_rate=0.0003, parameters=discriminator.parameters())
    source_label = paddle.zeros([batch_size, 1, 1, 1])
    target_label = paddle.ones([batch_size, 1, 1, 1])

    # use amp
    if fp16:
        logger.info('use amp to train')
        scaler = paddle.amp.GradScaler(init_loss_scaling=1024)

    if use_vdl:
        from visualdl import LogWriter
        log_writer = LogWriter(save_dir)

    avg_loss = 0.0

    reader_cost_averager = TimeAverager()

    batch_start = time.time()

    iter = start_iter
    while iter < iters:
        for data in loader:
            iter += 1

            if iter > iters:
                version = paddle.__version__
                if version == '2.1.2' or version == '0.0.0':
                    continue
                else:
                    break
            reader_cost_averager.record(time.time() - batch_start)
            images1 = data[0]
            images2 = data[1]
            labels = data[2].astype('int64')

            edges = None
            if len(data) == 4:
                edges = data[3].astype('int64')
            if hasattr(model, 'data_format') and model.data_format == 'NHWC':
                images1 = images1.transpose((0, 2, 3, 1))
                images2 = images2.transpose((0, 2, 3, 1))

            if fp16:
                with paddle.amp.auto_cast(
                        enable=True,
                        custom_white_list={
                            "elementwise_add", "batch_norm", "sync_batch_norm"
                        },
                        custom_black_list={'bilinear_interp_v2'}):
                    if nranks > 1:
                        logits_list = ddp_model(images1, images2)
                    else:
                        logits_list = model(images1, images2)
                    loss_list = loss_computation(
                        logits_list=logits_list,
                        labels=labels,
                        losses=losses,
                        edges=edges)
                    loss = sum(loss_list)

                scaled = scaler.scale(loss)  # scale the loss
                scaled.backward()  # do backward
                if isinstance(optimizer, paddle.distributed.fleet.Fleet):
                    scaler.minimize(optimizer.user_defined_optimizer, scaled)
                else:
                    scaler.minimize(optimizer, scaled)  # update parameters
            else:
                if nranks > 1:
                    logits_list = ddp_model(images1, images2)
                else:
                    for param in discriminator.parameters():
                        param.stop_gradient = True
                    logits_list = model(images1, images2)

                # 预测图与特征分开
                pred, x1, x2 = logits_list[0], logits_list[1], logits_list[2]
                loss_list = loss_computation(
                    logits_list=[pred],
                    labels=labels,
                    losses=losses,
                    edges=edges)

                loss = sum(loss_list)
                loss.backward()

                # 对抗训练来骗过判别器
                d_out_tar = discriminator(x2)
                loss_adv_trg = bce_loss(d_out_tar, source_label)
                loss_adv_trg.backward()

                # 训练判别器网络
                for param in discriminator.parameters():
                    param.stop_gradient = False
                # 判别器学习源域样本
                src_x1 = x1.detach()
                d_out_src = discriminator(src_x1)
                loss_d_src = bce_loss(d_out_src, source_label)
                loss_d_src = loss_d_src / 2
                loss_d_src.backward()

                # 判别器学习目标域样本
                tar_x2 = x2.detach()
                d_out_tar = discriminator(tar_x2)
                loss_d_tar = bce_loss(d_out_tar, target_label)
                loss_d_tar = loss_d_tar / 2
                loss_d_tar.backward()

                optimizer.step()
                optimizer.clear_grad()
                optimizer_d.step()
                optimizer_d.clear_grad()

            lr = optimizer.get_lr()

            # update lr
            if isinstance(optimizer, paddle.distributed.fleet.Fleet):
                lr_sche = optimizer.user_defined_optimizer._learning_rate
            else:
                lr_sche = optimizer._learning_rate
            if isinstance(lr_sche, paddle.optimizer.lr.LRScheduler):
                lr_sche.step()

            # model.clear_gradients()
            avg_loss += loss.numpy()[0]

`

按修改后的运行，然后报错：
`Traceback (most recent call last):
  File "/home/aistudio/PaddleAA1130/train.py", line 199, in <module>
    main(args)
  File "/home/aistudio/PaddleAA1130/train.py", line 193, in main
    fp16=args.fp16)
  File "/home/aistudio/PaddleAA1130/paddleseg/core/train.py", line 217, in train
    loss_adv_trg.backward()
  File "<decorator-gen-128>", line 2, in backward
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 229, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 249, in backward
    framework._dygraph_tracer())
RuntimeError: (NotFound) Inputs and outputs of elementwise_add_grad do not exist. This may be because:
1. You use some output variables of the previous batch as the inputs of the current batch. Please try to call "stop_gradient = True" or "detach()" for these variables.
2. You calculate backward twice for the same subgraph without setting retain_graph=True. Please set retain_graph=True in the first backward call.

  [Hint: Expected ins_.empty() && outs_.empty() != true, but received ins_.empty() && outs_.empty():1 == true:1.] (at /paddle/paddle/fluid/imperative/op_base.h:164)

Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved 1.532273.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved 1.236200.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved 1.122789.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved 1.324533.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved 1.255502.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved 1.172587.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved 1.302512.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved 1.212706.`

主要是说在    loss.backward()处，即第二次反向传播计算梯度的时候出现了问题，然后我按照提示将第一个backward()改为  loss.backward(retain_graph=True)，  但是还是有问题
`model load from /home/aistudio/.cache/paddle/hapi/weights/resnet18.pdparams /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/norm.py:653: UserWarning: 
When training, we now always track global mean and variance. 
"When training, we now always track global mean and variance.") /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py:253: 
UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.float32, but right dtype is paddle.int64, 
the right dtype will convert to paddle.float32 format(lhs_dtype, rhs_dtype, lhs_dtype)) 
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion (x >= static_cast(0)) && (x <= one)failed. 
Input is expected to be within the interval [0, 1], but recieved 1.435637. 
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion(x >= static_cast(0)) && (x <= one)failed. 
Input is expected to be within the interval [0, 1], but recieved 1.256481. 
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion(x >= static_cast(0)) && (x <= one)failed. 
Input is expected to be within the interval [0, 1], but recieved 1.124513. 
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion(x >= static_cast(0)) && (x <= one)failed. 
Input is expected to be within the interval [0, 1], but recieved 1.388019. 
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion(x >= static_cast(0)) && (x <= one)failed. 
Input is expected to be within the interval [0, 1], but recieved 1.174520. 
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion(x >= static_cast(0)) && (x <= one)failed. 
Input is expected to be within the interval [0, 1], but recieved 1.241708. 
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion(x >= static_cast(0)) && (x <= one)failed. 
Input is expected to be within the interval [0, 1], but recieved 1.432336. 
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion(x >= static_cast(0)) && (x <= one) failed. 
Input is expected to be within the interval [0, 1], but recieved 1.203197. 
Traceback (most recent call last): File "/home/aistudio/PaddleAA1130/train.py", line 199, in <module> main(args) 
File "/home/aistudio/PaddleAA1130/train.py", line 193, in main fp16=args.fp16) 
File "/home/aistudio/PaddleAA1130/paddleseg/core/train.py", line 252, in train avg_loss += loss.numpy()[0] 
OSError: (External) CUDA error(719), unspecified launch failure. 
[Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. 
Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. 
Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. 
This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. 
To continue using CUDA, the process must be terminated and relaunched.] (at /paddle/paddle/fluid/platform/gpu_info.cc:441)`

请问paddle如何写，能正确处理这种需要多次backward的方法呢？求解答。

**Comment by shiyutang** [comment]
在你的报错信息种可以看到，你的网络在bce_loss_op 存在输入数据错误，所以导致在增加损失的时候会爆CUDA719这往往提示输入数据的问题，因此需要查看你的label是否出现了浮点数。

**Comment by henryccl** [comment]
确实是预测值的问题，已解决！感谢解答！！！
